name: Github Pages

on:
  push:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playground
          path: dist/

  build-for-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            base_path: ${{ vars.BASE_PATH }}
          - branch: develop
            base_path: ${{ vars.BASE_PATH }}/develop
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
        env:
          BASE_PATH: ${{ matrix.base_path }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: playground-${{ matrix.branch }}
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [build-for-deployment]
    steps:
      - name: Fetch main build
        uses: actions/download-artifact@v3
        with:
          name: playground-main
          path: ${{ github.workspace }}/dist
      - name: Fetch develop build
        uses: actions/download-artifact@v3
        with:
          name: playground-develop
          path: ${{ github.workspace }}/dist/develop
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: ${{ vars.PAGES_CNAME }}
