name: Embeddable library

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build -- --mode library
      - name: Build library with external Svelte
        run: npm run build -- --mode library-external-svelte
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "<>"
          git config --global user.name "Automatic library publish"
          git add -f dist/*
          git commit -m "Publish library (${GITHUB_SHA})"
          git push -f origin "${GITHUB_REF_NAME}:library"
